apiVersion: v1
kind: Pod
metadata:
    name: multi-container

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort : 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]


#kubectl apply -f multi-container.yaml 
#kubectl get pods
#kubectl exec -it multi-container -c almalinux --bash
# all containers shared same storage and network.
# here almalinux contanier still able to access local host.
#curl localhost
